---
- hosts: servers
  become: yes
  vars:
    zabbix_server: "51.250.82.46"
    zabbix_hostname: "{{ ansible_hostname }}"
  tasks:

  - name: Install Zabbix agent package
    apt:
      name: zabbix-agent
      state: present

  - name: Configure Zabbix agent
    lineinfile:
      state: present
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^(\s*)[#]?{{ item.search }}(: )*'
      line: '{{ item.replace }}'
    with_items:
     - { search: '^Hostname=', replace: 'Hostname={{ zabbix_hostname }}' }
     - { search: '^Server=127.0.0.1', replace: 'Server={{ zabbix_server }}' }
     - { search: '^ServerActive=', replace: 'ServerActive={{ zabbix_server }}' }

  - name: Start and enable Zabbix agent service
    service:
     name: zabbix-agent
     state: started
     enabled: yes
